events/config/routes.rb
Rails.application.routes.draw do

  root 'events#index'
  resources :events do
    resources :registrations
  end


end

events/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

events/app/models/event.rb
class Event < ApplicationRecord
  validates :name, :description, :location, presence: true
  validates :description, length: {minimum: 25}
  validates :price, numericality: { greater_than_or_equal_to: 0}
  validates :capacity, numericality: {only_integer: true, greater_than: 0}
  validates :image_file_name, allow_blank: true, format: {
    with: /\w+\.(gif|jpg|png)\z/i,
    message: "Must reference a GIF, JPN or PNG image"
  }

  has_many :registrations, dependent: :destroy

  def free?
    price.blank? || price.zero?
  end

  def self.upcoming
    where("starts_at >= ?", Time.now).order("starts_at")
  end
end

events/app/models/registration.rb
class Registration < ApplicationRecord
validates :name, format: { with: /(\S+)@(\S+)/}

HOW_HEARD_OPTIONS = [
  'Newsletter',
  'Blog Post',
  'Twitter',
  'Web Search',
  'Friend/Coworker',
  'Other'
]

validates :how_heard,
            inclusion: { in: HOW_HEARD_OPTIONS }

  belongs_to :event
end

events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

events/app/controllers/events_controller.rb
class EventsController < ApplicationController


  def index
    @events = Event.upcoming

  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
  @event = Event.find(params[:id])
    if
    @event.update(event_params)

    redirect_to @event, notice: "Event sucessfuly updated!"
    else
      render 'edit'
    end
  end

def new
    @event = Event.new
end

def create
  @event = Event.new(event_params)

  if @event.save
  redirect_to @event
  else
    render 'new'
  end
end

def destroy
  @event = Event.find(params[:id])
  @event.destroy
  redirect_to @event
end

private

def event_params
  params.require(:event).
  permit(:name, :description, :location, :price, :starts_at, :image_file_name, :capacity)
end


end

events/app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

  def index
    @event = Event.find(params[:event_id])
    @registrations = @event.registrations
  end

  def new
      @event = Event.find(params[:event_id])
      @registration = @event.registrations.new
  end

  def edit

  end

  def create
    @event = Event.find(params[:event_id])
      @registrtion = @event.registrations.new(registration_params)
      if @registration.save
        redirect_to event_registrations_path(@event),
                        notice: "Thanks, you're registed!"
      else
        render 'new'
      end
  end

  private

  def registration_params
    params.require(:registration).permit(:name, :email, :how_heard)
  end

end

events/app/helpers/application_helper.rb
module ApplicationHelper
end

events/app/helpers/events_helper.rb
module EventsHelper
  def format_price(event)
    if event.free?
      content_tag(:strong, "Free!")
      else
        number_to_currency(event.price)
    end
  end

  def image_for(event)
    if event.image_file_name.blank?
      image_tag 'placeholder.png'
    else
      image_tag event.image_file_name
    end
  end
end

events/app/helpers/registrations_helper.rb
module RegistrationsHelper
end

events/app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= @event.errors.full_messages.to_s %>
<p>
  <%= f.label :name %><br/>
  <%= f.text_field :name, autofocus: true %>
</p>
<p>
  <%= f.label :description %><br/>
  <%= f.text_area :description, cols:40, rows:7 %>
</p>
<p>
  <%= f.label :location %><br/>
  <%= f.text_field :location %>
</p>
<p>
  <%= f.label :price %><br/>
  <%= f.number_field :price %>
</p>
<p>
  <%= f.label :starts_at %><br/>
  <%= f.datetime_select :starts_at %>
</p>
 <p>
    <%= f.label :image_file_name %><br/>
    <%= f.text_field :image_file_name, size:30,
        placeholder: "GIF, JPG or PNG file name" %>
  </p>
  <p>
  <%= f.label :capacity %><br/>
  <%= f.number_field :capacity %>
</p>

<%= f.submit %>
<%= link_to "Cancel", events_path %>
<% end %>

events/app/views/events/edit.html.erb
<h1><%= @event.name %> </h1>

<%= render 'form' %>

events/app/views/events/index.html.erb
<h1><%= pluralize(@events.size, 'Event') %></h1>

<% @events.each do |event| %>
  <article class="event">
    <header>
    <%=  image_for(event) %>
      <h2><%= link_to event.name, event %></h2>
      <h3><%= pluralize(event.capacity, 'spot') %></h3>
    </header>
    <p>
      <%= truncate(event.description, length: 35, separator: ' ') %>
    </p>
    <table>
      <tr>
        <th>When:</th>
        <td><%= event.starts_at %></td>
      </tr>
      <tr>
        <th>Where:</th>
        <td><%= event.location %></td>
      </tr>
      <tr>
        <th>Price:</th>
        <td><%= format_price(event) %></td>
      </tr>
    </table>
  </article>
<% end %>

events/app/views/events/new.html.erb
<h1>New Event </h1>

<%= render 'form' %>

events/app/views/events/show.html.erb
<article>
  <header>
  <%= image_for(@event) %>
    <h1><%= @event.name %></h1>
  </header>
  <p>
    <%= @event.description %>
  </p>
  <h3>When</h3>
  <p>
    <%= @event.starts_at %>
  </p>
  <h3>Where</h3>
  <p>
    <%= @event.location %>
  </p>
  <h3>Price</h3>
  <p>
    <%= format_price(@event) %>
  </p>
</article>

<%= link_to "Who's registrated?", event_registrations_path(@event) %>
<footer>
<%= link_to "Register!", new_event_registration_path(@event), class: "button ok register" %>
  <nav>
<%= link_to "Edit It", edit_event_path(@event), class: 'button' %> |
<%= link_to 'Delete', @event,
                    class: 'button',
                   method: :delete,
                   data: { confirm: 'Are you sure?' } %>
  </nav>
</footer>

events/app/views/layouts/_aside.html.erb
<aside id = "sidebar" = "background: #F0F0F0;
                   width: 200px;
                  float: right;">
    <nav>
      <ul>
        <li>
          <%= link_to "All Events", events_path %>
        </li>
        <li>
        <%= link_to "Add New Event", new_event_path %>
        </li>
      </ul>
    </nav>
    </aside>

events/app/views/layouts/_footer.html.erb
 <footer id = "page-footer" = "background: #F0F0F0;
                     color: 237CBE;">
    <p>
    Copyrighy &copy; 2016 Tess's practice
    </p>
    </footer>

events/app/views/layouts/_header.html.erb
<header id = "page-header" = "color:#F0F0F0;
                    background: #237CBE;">
  <h1>Tess's Events</h1>
  </header>

events/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Events</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>

<%= flash[:notice] %>
  <%= render 'layouts/aside' %>
    <%= yield %>
   <%= render 'layouts/footer' %>
  </body>
</html>