rails101-1/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :groups do
    resources :posts
  end
  root 'groups#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

rails101-1/app/models/group.rb
class Group < ApplicationRecord
  validates :title, presence: true
  has_many :posts
  belongs_to :owner, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user && user == owner
  end
end

rails101-1/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :group
  validates :content, presence: true
  belongs_to :author, class_name: "User", foreign_key: :user_id

  def editable_by?(user)
    user && user == author
  end
end

rails101-1/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :groups
  has_many :posts
end

rails101-1/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
       u.permit(:name, :email, :password, :password_confirmation)
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
   end
  end
end

rails101-1/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  def index
    @groups = Group.all

  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find(params[:id])
    @posts = @group.posts
  end

def edit
  @group = current_user.groups.find(params[:id])
end

def update
  @group = current_user.groups.find(params[:id])

  if @group.update(group_params)
    redirect_to group_path, notice: "修改討論版成功"
    else
      render 'edit'
  end
end

def destroy
  @group = current_user.groups.find(params[:id])
  @group.destroy
  redirect_to groups_path, alert: "討論版已刪除"
end

def create
  @group = current_user.groups.new(group_params)

  if @group.save
    redirect_to groups_path
  else
    render 'new'
  end
end

private

def group_params
  params.require(:group).permit(:title, :description)
end

end

rails101-1/app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :find_group
before_action :authenticate_user!

def new
  @post = @group.posts.new
end

def edit
  @group = Group.find(params[:group_id])
  @post = current_user.posts.find(params[:id])
end

def create
  @post = @group.posts.build(post_params)
  @post.author = current_user

  if @post.save
    redirect_to group_path(@group), notice: "新增文章成功！"
  else
    render 'new'
    end
  end


def update
  @post = current_user.posts.find(params[:id])

  if @post.update(post_params)
    redirect_to group_path(@group), notice: "文章修改成功！"
  else
    render 'edit'
  end
end


  def destroy
    @post = current_user.posts.find(params[:id])

    @post.destroy
    redirect_to group_path(@group), alert: "文章已刪除"
  end

  private

  def find_group
    @group = Group.find(params[:group_id])
  end

  def post_params
    params.require(:post).permit(:content)
  end
end

rails101-1/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

rails101-1/app/helpers/groups_helper.rb
module GroupsHelper
end

rails101-1/app/helpers/posts_helper.rb
module PostsHelper
end

rails101-1/app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2016 Tess105
    <br>Design by <a href="https://github.com/Tess10553" target=_new>Tess Yu</a>
  </p>
</footer>

rails101-1/app/views/common/_navbar.html.erb
<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Tess Yu's Open Topic</a>
      <img alt='tess' src="#">
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

       <% if !current_user %>
         <li> <%= link_to("註冊", new_user_registration_path) %> </li>

         <li> <%= link_to("登入", new_user_session_path) %> </li>
       <% else %>
         <li class="dropdown">
           <a href="#" class="dropdown-toggle" data-toggle="dropdown">
             Hi!, <%= current_user.name %>
             <b class="caret"></b>
           </a>
          <ul class="dropdown-menu">
            <li><%= link_to("帳號設定", edit_user_registration_path)%></li>
             <li> <%= link_to("登出", destroy_user_session_path, method: :delete) %> </li>
           </ul>
         </li>
       <% end %>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

rails101-1/app/views/groups/edit.html.erb
<div class='col-md-4 col-md-offset-4' >
<h1>修改討論區</h1>

<hr>
<%= simple_form_for @group do |f| %>
<div class='form-group'>
<%= f.input :title %>
<%= f.input :description %>
</div>
<%= f.submit "submit", class: 'btn btn-primary', data: {disable_with: "srbmitting..."} %>
<% end %>
</div>

rails101-1/app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
          <% if group.editable_by?(current_user) %>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
                          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

rails101-1/app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
  <h1>新增討論版</h1>

  <hr>
  <%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
      <%= f.input :description, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
  <% end %>
</div>

rails101-1/app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
  <%= link_to("New Post", new_group_post_path(@group), class: "btn btn-warning pull-right") %>
  <% if @group.editable_by?(current_user) %>
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
  <% end %>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>
<table class='table' >
<thead>
  <tr>
  <th>文章 </th>
  <th colspan="2"></th>
  </tr>
</thead>
<tbody>
<% @posts.each do |post| %>
<tr>
<td><%= post.content %></td>
<td>
<% if post.editable_by?(current_user) %>
<%= link_to("Edit", edit_group_post_path(post.group, post),class: "btn btn-default btn-xs") %>
<%= link_to("Delete", group_post_path(post.group, post), class: "btn btn-default btn-xs", method: :delete, data: {confirm: "Are you sure?"}) %>
<% end %>
</td>
</tr>
<% end %>
</tbody>
</table>

</div>

rails101-1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails1011</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container-fluid" >
  <%= render 'common/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
    <%= render 'common/footer' %>
  </body>
</html>

rails101-1/app/views/posts/new.html.erb
<h1 class='text-center'>新增文章</h1>

<div class='col-md-4 col-md-offset-4'>
<%= simple_form_for [@group,@post] do |f| %>
<div class='form-group'>
<%= f.input :content, input_html: {class: "form-control"} %>
</div>
<div class='form-actions'>
<%= f.submit "Submit", disable_with: "submitting...", class: "btn btn-primary" %>
</div>
<% end %>
</div>

rails101-1/app/views/welcome/index.html.erb
<h1>Hellow world</h1>